# Generated by Django 2.2.5 on 2020-06-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataLog',
            fields=[
                ('UUID', models.AutoField(primary_key=True, serialize=False)),
                ('associate', models.CharField(blank='False', max_length=100, null='False')),
                ('date', models.DateField(blank='True', null='True')),
                ('performed_date', models.DateField(blank='True', null='True')),
                ('month', models.CharField(blank='False', max_length=15, null='False')),
                ('task', models.CharField(blank='False', max_length=100, null='False')),
                ('Sub_Task', models.CharField(blank='False', max_length=500, null='False')),
                ('filename', models.CharField(blank='False', max_length=100, null='False')),
                ('volume', models.CharField(blank='False', max_length=100, null='False')),
                ('hours_spent', models.DecimalField(blank='True', decimal_places=2, max_digits=10, null='True')),
                ('Productivity', models.IntegerField(blank='False', null='False')),
                ('status', models.CharField(blank='False', max_length=15, null='False')),
                ('accuracy', models.CharField(blank='False', max_length=100, null='False')),
                ('aoa_by', models.CharField(blank='False', max_length=500, null='False')),
                ('auditor_comments', models.CharField(blank='False', max_length=500, null='False')),
                ('aoa_comments', models.CharField(blank='False', max_length=500, null='False')),
            ],
        ),
        migrations.CreateModel(
            name='task_information',
            fields=[
                ('Task_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Task', models.CharField(blank='False', max_length=100, null='False')),
                ('Sub_Task', models.CharField(blank='False', max_length=100, null='False')),
                ('volume', models.IntegerField(blank='False', null='False')),
                ('benchmark', models.DecimalField(blank='True', decimal_places=2, max_digits=5, null='True')),
            ],
        ),
    ]
