# Generated by Django 2.2.5 on 2020-06-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank='False', max_length=100, null='False')),
                ('login_status', models.CharField(blank='False', max_length=100, null='False')),
                ('login_time', models.DateTimeField(blank='True', null='True')),
                ('benchmark_hours', models.IntegerField(blank='False', null='False')),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank='False', max_length=50, null='False')),
                ('user_role', models.CharField(blank='False', max_length=50, null='False')),
            ],
        ),
    ]
